# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
- master

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: echo hello from Linux

  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: '03db7951-faab-44df-a0dd-5bfcd6734227'
      organization: 'jfpanisset-github'
      scannerMode: 'CLI'
      configMode: 'manual'
      cliProjectKey: 'jfpanisset_openexr'
      cliProjectName: 'openexr'
  - task: CMake@1
    inputs:
      cmakeArgs: '-DCMAKE_INSTALL_PREFIX=/usr/local . -G "Unix Makefiles" -DCMAKE_PREFIX_PATH=/usr/local'
    displayName: Generate Makefiles with Cmake on Linux
  - bash: |
      make
    displayName: Build OpenEXR on Linux

- job: macOS
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - script: echo hello from macOS
  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: '03db7951-faab-44df-a0dd-5bfcd6734227'
      organization: 'jfpanisset-github'
      scannerMode: 'CLI'
      configMode: 'manual'
      cliProjectKey: 'jfpanisset_openexr'
      cliProjectName: 'openexr'
  - task: CMake@1
    inputs:
      cmakeArgs: '-DCMAKE_INSTALL_PREFIX=/usr/local . -G "Unix Makefiles" -DCMAKE_PREFIX_PATH=/usr/local'
    displayName: Generate Makefiles with Cmake on macOS    
  - bash: |
      make
    displayName: Run cmake and build OpenEXR on macOS
   
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: echo hello from Windows
  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: '03db7951-faab-44df-a0dd-5bfcd6734227'
      organization: 'jfpanisset-github'
      scannerMode: 'CLI'
      configMode: 'manual'
      cliProjectKey: 'jfpanisset_openexr'
      cliProjectName: 'openexr'
  - task: CMake@1
    inputs:
      cmakeArgs: . -G "Visual Studio 15 2017 Win64"
    displayName: Generate Visual Studio Solution with CMake on Windows
  - task: MSBuild@1
    inputs:
      solution: '*.sln'
    displayName: Build OpenEXR on Windows

