# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc


trigger:
- master

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: echo hello from Linux
  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'fc625b8f-ccd1-4739-8296-af200d3aac70'
      organization: 'jfpanisset-github'
      scannerMode: 'CLI'
      configMode: 'manual'
      cliProjectKey: 'jfpanisset_openexr'
      cliProjectName: 'openexr'
  - bash: |
      cmake -DCMAKE_INSTALL_PREFIX=/usr/local . -G "Unix Makefiles" -DCMAKE_PREFIX_PATH=/usr/local
      make
    displayName: Run cmake and build OpenEXR on Linux

- job: macOS
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - script: echo hello from macOS
  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'fc625b8f-ccd1-4739-8296-af200d3aac70'
      organization: 'jfpanisset-github'
      scannerMode: 'CLI'
      configMode: 'manual'
      cliProjectKey: 'jfpanisset_openexr'
      cliProjectName: 'openexr'
  - bash: |
      cmake -DCMAKE_INSTALL_PREFIX=/usr/local . -G "Unix Makefiles" -DCMAKE_PREFIX_PATH=/usr/local
      make
    displayName: Run cmake and build OpenEXR on macOS
   
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: echo hello from Windows
  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'fc625b8f-ccd1-4739-8296-af200d3aac70'
      organization: 'jfpanisset-github'
      scannerMode: 'CLI'
      configMode: 'manual'
      cliProjectKey: 'jfpanisset_openexr'
      cliProjectName: 'openexr'
  - powershell: |
      Remove-Item -Force -ErrorAction Ignore CMakeCache.txt
      Start-Process -FilePath cmake -ArgumentList "-G `"Visual Studio 15 2017 Win64`""
    displayName: Run cmake on Windows
  - task: MSBuild@1
    solution: '*.sln'
    displayName: Build OpenEXR on Windows

